# Generated by Django 5.1.1 on 2024-09-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_artista', models.CharField(max_length=120)),
                ('foto_artista', models.ImageField(blank=True, null=True, upload_to='')),
                ('profilo', models.TextField(blank=True, null=True)),
                ('sites', models.CharField(blank=True, max_length=100, null=True)),
                ('componenti', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artisti',
            },
        ),
        migrations.CreateModel(
            name='Stile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stile', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Stile',
                'verbose_name_plural': 'Stili',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_album', models.CharField(max_length=140)),
                ('editore', models.CharField(blank=True, max_length=20, null=True)),
                ('catalogo', models.CharField(blank=True, max_length=16, null=True)),
                ('genere', models.CharField(blank=True, max_length=10, null=True)),
                ('supporto', models.CharField(blank=True, max_length=10, null=True)),
                ('data_rilascio', models.DateField(blank=True, null=True)),
                ('deposito', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('copertina', models.ImageField(blank=True, null=True, upload_to='')),
                ('costo', models.FloatField(default=0, help_text='in EU €')),
                ('closed', models.BooleanField(default=False)),
                ('artista_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artista')),
                ('stili', models.ManyToManyField(blank=True, to='music.stile')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Brano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_brano', models.CharField(max_length=50)),
                ('sezione', models.CharField(blank=True, max_length=2, null=True)),
                ('progressivo', models.CharField(blank=True, max_length=2, null=True)),
                ('crediti', models.CharField(blank=True, max_length=100, null=True)),
                ('durata', models.CharField(blank=True, max_length=5, null=True)),
                ('album_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brani', to='music.album')),
            ],
            options={
                'verbose_name': 'Brano',
                'verbose_name_plural': 'Brani',
            },
        ),
    ]
