# Generated by Django 5.2.7 on 2025-11-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_catalogo_alter_album_editore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brano',
            name='progressivo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='brano',
            name='titolo_brano',
            field=models.CharField(max_length=150),
        ),
    ]
