# Generated by Django 5.2.7 on 2026-08-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_albumdesiderato'),
    ]

    operations = [
        migrations.AddField(
            model_name='brano',
            name='ascolto_fonte',
            field=models.CharField(blank=True, choices=[('bandcamp', 'Bandcamp'), ('youtube', 'YouTube')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='brano',
            name='ascolto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
